#!/bin/bash
paru -Syu --needed --noconfirm \
    vivaldi-snapshot \
    vivaldi-snapshot-ffmpeg-codecs \
    pipewire \
    pipewire-alsa \
    pipewire-audio \
    pipewire-docs \
    pipewire-ffado \
    pipewire-jack \
    pipewire-libcamera \
    pipewire-pulse \
    pipewire-roc \
    pipewire-v4l2 \
    pipewire-x11-bell \
    pipewire-zeroconf \
    qemu-audio-pipewire \
    gst-plugin-pipewire \
    libpipewire \
    lib32-libpipewire \
    lib32-pipewire \
    lib32-pipewire-jack \
    lib32-pipewire-v4l2 \
    wireplumber \
    wireplumber-docs \
    libwireplumber \
    tmux \
    obs-studio \
    flatpak \
    steam \
    lutris \
    wine \
    winetricks \
    wine-mono \
    wine-gecko \
    gamemode \
    lib32-gamemode \
    mesa \
    lib32-mesa \
    xf86-video-amdgpu \
    vulkan-tools \
    lib32-vulkan-icd-loader \
    vulkan-icd-loader \
    vulkan-radeon \
    lib32-vulkan-radeon \
    ttf-liberation \
    ttf-liberation-mono-nerd \
    libvirt \
    libvirt-dbus \
    libvirt-glib \
    libvirt-python \
    libvirt-storage-gluster \
    libvirt-storage-iscsi-direct \
    qemu-audio-alsa \
    qemu-audio-dbus \
    qemu-audio-pipewire \
    qemu-audio-sdl \
    qemu-audio-spice \
    qemu-base \
    qemu-block-curl \
    qemu-block-iscsi \
    qemu-block-nfs \
    qemu-block-ssh \
    qemu-chardev-baum \
    qemu-chardev-spice \
    qemu-common \
    qemu-desktop \
    qemu-docs \
    qemu-emulators-full \
    qemu-guest-agent \
    qemu-hw-display-qxl \
    qemu-hw-display-virtio-gpu \
    qemu-hw-display-virtio-gpu-gl \
    qemu-hw-display-virtio-gpu-pci \
    qemu-hw-display-virtio-gpu-pci-gl \
    qemu-hw-uefi-vars \
    qemu-hw-usb-host \
    qemu-hw-usb-redirect \
    qemu-img \
    qemu-system-x86 \
    qemu-system-x86-firmware \
    qemu-tools \
    qemu-ui-egl-headless \
    qemu-ui-gtk \
    qemu-ui-opengl \
    qemu-ui-sdl \
    qemu-ui-spice-app \
    qemu-ui-spice-core \
    qemu-user \
    qemu-user-static \
    qemu-user-static-binfmt \
    virt-manager \
    dnsmasq \
    openbsd-netcat \
    dmidecode \
    jdk-temurin \
    ttf-ms-win11-auto
